
-- V1__Init_Security_Tables.sql

-- Create roles table
CREATE TABLE IF NOT EXISTS roles (
    id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::text,
    ref VARCHAR(500) UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6)
);

CREATE INDEX IF NOT EXISTS idx_roles_name ON roles(name);

-- Hibernate Envers revision tracking
CREATE TABLE IF NOT EXISTS revinfo (
    rev     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

-- Create users table with dynamic fields based on configuration
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY DEFAULT gen_random_uuid()::text,
    ref VARCHAR(500) UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone_number VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_enabled BOOLEAN DEFAULT TRUE,
    is_locked BOOLEAN DEFAULT FALSE,
    is_credentials_expired BOOLEAN DEFAULT FALSE,
    is_email_verified BOOLEAN DEFAULT FALSE,
    is_phone_verified BOOLEAN DEFAULT FALSE,
    auth_provider VARCHAR(50) NOT NULL DEFAULT 'LOCAL',
    provider_subject VARCHAR(255) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    avatar_url VARCHAR(255),
    bio VARCHAR(255),
    job_title VARCHAR(255),
    storage_used_bytes BIGINT,
    storage_quota_bytes BIGINT,
    last_seen_at TIMESTAMP(6),
    total_documents_uploaded INTEGER,
    is_suspended BOOLEAN,
    suspended_reason VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Create users_roles join table
CREATE TABLE IF NOT EXISTS users_roles (
    users_id VARCHAR(255) NOT NULL,
    roles_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (users_id, roles_id),
    FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (roles_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_users_roles_role_id ON users_roles(roles_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_active ON users(email) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone_active ON users(phone_number) WHERE deleted_at IS NULL;

-- Create application entity tables (PostgreSQL, excluding User)
CREATE TABLE IF NOT EXISTS app_organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    logo_url VARCHAR(255),
    website VARCHAR(255),
    storage_used_bytes BIGINT,
    storage_quota_bytes BIGINT,
    max_members INTEGER,
    is_active BOOLEAN,
    billing_email VARCHAR(255),
    plan_tier VARCHAR(255),
    trial_ends_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_organization_ref ON app_organization(ref);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_organization_slug_active ON app_organization(slug) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS app_organizationrequest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    requested_name VARCHAR(255) NOT NULL,
    requested_slug VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    intended_use VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    reviewed_at TIMESTAMP(6),
    rejection_reason VARCHAR(255),
    created_organization_id BIGINT,
    requested_by_user_id VARCHAR(255) NOT NULL,
    reviewed_by_user_id VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_organizationrequest_ref ON app_organizationrequest(ref);
CREATE INDEX IF NOT EXISTS idx_app_organizationrequest_requested_by_user_id ON app_organizationrequest(requested_by_user_id);
CREATE INDEX IF NOT EXISTS idx_app_organizationrequest_reviewed_by_user_id ON app_organizationrequest(reviewed_by_user_id);

CREATE TABLE IF NOT EXISTS app_organizationmember (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    member_role VARCHAR(255) NOT NULL,
    joined_at TIMESTAMP(6),
    is_active BOOLEAN,
    invited_by_email VARCHAR(255),
    organization_id BIGINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_organizationmember_ref ON app_organizationmember(ref);
CREATE INDEX IF NOT EXISTS idx_app_organizationmember_organization_id ON app_organizationmember(organization_id);
CREATE INDEX IF NOT EXISTS idx_app_organizationmember_user_id ON app_organizationmember(user_id);

CREATE TABLE IF NOT EXISTS app_organizationinvitation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    invitee_email VARCHAR(255) NOT NULL,
    intended_role VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) NOT NULL,
    accepted_at TIMESTAMP(6),
    organization_id BIGINT NOT NULL,
    invited_by_user_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_organizationinvitation_ref ON app_organizationinvitation(ref);
CREATE INDEX IF NOT EXISTS idx_app_organizationinvitation_organization_id ON app_organizationinvitation(organization_id);
CREATE INDEX IF NOT EXISTS idx_app_organizationinvitation_invited_by_user_id ON app_organizationinvitation(invited_by_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_organizationinvitation_token_active ON app_organizationinvitation(token) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS app_folder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    color VARCHAR(255),
    icon_name VARCHAR(255),
    is_shared BOOLEAN,
    document_count INTEGER,
    total_size_bytes BIGINT,
    parent_folder_id BIGINT,
    organization_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_folder_ref ON app_folder(ref);
CREATE INDEX IF NOT EXISTS idx_app_folder_parent_folder_id ON app_folder(parent_folder_id);
CREATE INDEX IF NOT EXISTS idx_app_folder_organization_id ON app_folder(organization_id);

CREATE TABLE IF NOT EXISTS app_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL UNIQUE,
    mime_type VARCHAR(255) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    storage_bucket VARCHAR(255) NOT NULL,
    storage_key VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(255) NOT NULL,
    visibility VARCHAR(255) NOT NULL,
    current_version_number INTEGER,
    download_count INTEGER,
    view_count INTEGER,
    is_password_protected BOOLEAN,
    password_hash VARCHAR(255),
    expires_at TIMESTAMP(6),
    archived_at TIMESTAMP(6),
    checksum VARCHAR(255),
    ocr_status VARCHAR(255),
    ocr_text VARCHAR(255),
    ocr_processed_at TIMESTAMP(6),
    ocr_language VARCHAR(255),
    ocr_confidence_score NUMERIC(19,2),
    folder_id BIGINT,
    organization_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_document_ref ON app_document(ref);
CREATE INDEX IF NOT EXISTS idx_app_document_folder_id ON app_document(folder_id);
CREATE INDEX IF NOT EXISTS idx_app_document_organization_id ON app_document(organization_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_document_stored_filename_active ON app_document(stored_filename) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_document_storage_key_active ON app_document(storage_key) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS app_documentversion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    version_number INTEGER NOT NULL,
    label VARCHAR(255),
    change_note VARCHAR(255),
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL UNIQUE,
    storage_key VARCHAR(255) NOT NULL UNIQUE,
    file_size_bytes BIGINT NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    checksum VARCHAR(255),
    is_current_version BOOLEAN,
    ocr_status VARCHAR(255),
    ocr_text VARCHAR(255),
    document_id BIGINT NOT NULL,
    uploaded_by_user_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_documentversion_ref ON app_documentversion(ref);
CREATE INDEX IF NOT EXISTS idx_app_documentversion_document_id ON app_documentversion(document_id);
CREATE INDEX IF NOT EXISTS idx_app_documentversion_uploaded_by_user_id ON app_documentversion(uploaded_by_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_documentversion_stored_filename_active ON app_documentversion(stored_filename) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_documentversion_storage_key_active ON app_documentversion(storage_key) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS app_documentshare (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    share_token VARCHAR(255) NOT NULL UNIQUE,
    permission VARCHAR(255) NOT NULL,
    shared_with_email VARCHAR(255),
    is_public_link BOOLEAN,
    expires_at TIMESTAMP(6),
    is_revoked BOOLEAN,
    revoked_at TIMESTAMP(6),
    access_count INTEGER,
    last_accessed_at TIMESTAMP(6),
    requires_password BOOLEAN,
    password_hash VARCHAR(255),
    document_id BIGINT NOT NULL,
    shared_by_user_id VARCHAR(255) NOT NULL,
    shared_with_user_id VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_documentshare_ref ON app_documentshare(ref);
CREATE INDEX IF NOT EXISTS idx_app_documentshare_document_id ON app_documentshare(document_id);
CREATE INDEX IF NOT EXISTS idx_app_documentshare_shared_by_user_id ON app_documentshare(shared_by_user_id);
CREATE INDEX IF NOT EXISTS idx_app_documentshare_shared_with_user_id ON app_documentshare(shared_with_user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_documentshare_share_token_active ON app_documentshare(share_token) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS app_documentcomment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    content VARCHAR(255) NOT NULL,
    is_resolved BOOLEAN,
    resolved_at TIMESTAMP(6),
    page_number INTEGER,
    position_x NUMERIC(19,2),
    position_y NUMERIC(19,2),
    is_edited BOOLEAN,
    edited_at TIMESTAMP(6),
    document_id BIGINT NOT NULL,
    parent_comment_id BIGINT,
    author_user_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_documentcomment_ref ON app_documentcomment(ref);
CREATE INDEX IF NOT EXISTS idx_app_documentcomment_document_id ON app_documentcomment(document_id);
CREATE INDEX IF NOT EXISTS idx_app_documentcomment_parent_comment_id ON app_documentcomment(parent_comment_id);
CREATE INDEX IF NOT EXISTS idx_app_documentcomment_author_user_id ON app_documentcomment(author_user_id);

CREATE TABLE IF NOT EXISTS app_auditlog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    action VARCHAR(255) NOT NULL,
    actor_user_id VARCHAR(255),
    actor_email VARCHAR(255),
    target_entity_type VARCHAR(255),
    target_entity_id VARCHAR(255),
    organization_id BIGINT,
    metadata VARCHAR(255),
    ip_address VARCHAR(255),
    user_agent VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_auditlog_ref ON app_auditlog(ref);

CREATE TABLE IF NOT EXISTS app_notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    type VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(255) NOT NULL,
    read BOOLEAN,
    read_at TIMESTAMP(6),
    target_url VARCHAR(255),
    related_entity_type VARCHAR(255),
    related_entity_id VARCHAR(255),
    recipient_user_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_notification_ref ON app_notification(ref);
CREATE INDEX IF NOT EXISTS idx_app_notification_recipient_user_id ON app_notification(recipient_user_id);

CREATE TABLE IF NOT EXISTS app_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    color VARCHAR(255),
    usage_count INTEGER,
    organization_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_tag_ref ON app_tag(ref);
CREATE INDEX IF NOT EXISTS idx_app_tag_organization_id ON app_tag(organization_id);

CREATE TABLE IF NOT EXISTS app_searchindex (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    document_id BIGINT NOT NULL,
    document_title VARCHAR(255),
    full_text VARCHAR(255),
    ocr_text VARCHAR(255),
    tags VARCHAR(255),
    mime_type VARCHAR(255),
    organization_id BIGINT,
    owner_id VARCHAR(255),
    visibility VARCHAR(255),
    indexed_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_searchindex_ref ON app_searchindex(ref);


-- Create join tables for ManyToMany relationships (PostgreSQL)
CREATE TABLE IF NOT EXISTS app_document_tags (
    document_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (document_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_app_document_tags_tag_id ON app_document_tags(tag_id);

CREATE TABLE IF NOT EXISTS app_tag_documents (
    tag_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    PRIMARY KEY (tag_id, document_id)
);

CREATE INDEX IF NOT EXISTS idx_app_tag_documents_document_id ON app_tag_documents(document_id);


-- Insert initial roles from configuration
INSERT INTO roles (id, name, created_date, created_by) 
SELECT gen_random_uuid()::text, 'ROLE_ADMIN', NOW(), 'system'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN');

INSERT INTO roles (id, name, created_date, created_by) 
SELECT gen_random_uuid()::text, 'ROLE_USER', NOW(), 'system'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_USER');


