-- V4_1__Create_Department_Tables.sql
-- app_department, app_departmentroledefinition, app_departmentmember, and
-- app_departmentdocumentshare were never created by any prior migration, despite
-- V5/V6/V7 altering/referencing them — Department.java, DepartmentRoleDefinition.java,
-- DepartmentMember.java, and DepartmentDocumentShare.java are real JPA entities with no
-- backing table. This went unnoticed locally because the dev profile uses
-- ddl-auto: update (Hibernate silently created them); prod/staging use ddl-auto:
-- validate, which relies on Flyway alone and fails outright — V5's
-- ALTER TABLE app_departmentroledefinition is the first statement to hit a
-- table that was never there.
-- Versioned between V4 and V5 (not appended after V7) so it runs before the
-- migrations that already assume these tables exist.

CREATE TABLE IF NOT EXISTS app_departmentroledefinition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    name VARCHAR(100) NOT NULL,
    color VARCHAR(50),
    is_lead BOOLEAN,
    organization_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_departmentroledefinition_ref ON app_departmentroledefinition(ref);
CREATE INDEX IF NOT EXISTS idx_app_departmentroledefinition_organization_id ON app_departmentroledefinition(organization_id);

CREATE TABLE IF NOT EXISTS app_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    name VARCHAR(500) NOT NULL,
    description VARCHAR(500),
    color VARCHAR(50),
    is_active BOOLEAN,
    organization_id BIGINT NOT NULL,
    parent_department_id BIGINT,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_department_ref ON app_department(ref);
CREATE INDEX IF NOT EXISTS idx_app_department_organization_id ON app_department(organization_id);
CREATE INDEX IF NOT EXISTS idx_app_department_parent_department_id ON app_department(parent_department_id);

CREATE TABLE IF NOT EXISTS app_departmentmember (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    role_id BIGINT NOT NULL,
    joined_at TIMESTAMP(6),
    department_id BIGINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_departmentmember_ref ON app_departmentmember(ref);
CREATE INDEX IF NOT EXISTS idx_app_departmentmember_department_id ON app_departmentmember(department_id);
CREATE INDEX IF NOT EXISTS idx_app_departmentmember_user_id ON app_departmentmember(user_id);
CREATE INDEX IF NOT EXISTS idx_app_departmentmember_role_id ON app_departmentmember(role_id);

CREATE TABLE IF NOT EXISTS app_departmentdocumentshare (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ref VARCHAR(500) UNIQUE,
    created_date TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    last_modified_date TIMESTAMP(6),
    created_by VARCHAR(255) NOT NULL DEFAULT 'system',
    last_modified_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    deleted_at TIMESTAMP(6),
    permission VARCHAR(255) NOT NULL,
    shared_at TIMESTAMP(6),
    expires_at TIMESTAMP(6),
    department_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    shared_by_user_id VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_app_departmentdocumentshare_ref ON app_departmentdocumentshare(ref);
CREATE INDEX IF NOT EXISTS idx_app_departmentdocumentshare_department_id ON app_departmentdocumentshare(department_id);
CREATE INDEX IF NOT EXISTS idx_app_departmentdocumentshare_document_id ON app_departmentdocumentshare(document_id);
